## Numpy

In [1]:
import numpy as np

In [7]:
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [8]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [17]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [18]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [19]:
import pandas as pd

In [24]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [26]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.random.randint(0,10,size=(7,2))

array([[3, 0],
       [7, 7],
       [6, 3],
       [3, 1],
       [6, 2],
       [0, 0],
       [3, 9]])

In [38]:
np.random.random((3,5))

array([[0.9093204 , 0.25877998, 0.66252228, 0.31171108, 0.52006802],
       [0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894],
       [0.89482735, 0.59789998, 0.92187424, 0.0884925 , 0.19598286]])

In [39]:
np.random.seed(42)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [41]:
b = np.random.randint(1,10,size=(3,7))
b

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [43]:
np.unique(b)

array([1, 2, 3, 4, 5, 7, 9])

In [44]:
b[0]

array([9, 1, 3, 7, 4, 9, 3])

In [48]:
b[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [51]:
b[0:2,0:2]

array([[9, 1],
       [5, 3]])

In [52]:
a4 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [54]:
a4, ones

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [56]:
a4 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [61]:
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
a4-ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [63]:
a4*ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [65]:
a4 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [66]:
np.square(a4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [67]:
np.mean(a4)

3.8666666666666667

In [68]:
np.max(a4)

9

In [69]:
np.min(a4)

0

In [70]:
np.std(a4)

2.578543947441829

In [71]:
np.var(a4)

6.648888888888889

In [72]:
a4.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [73]:
a4.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

In [74]:
mat1 = np.random.randint(10,size=(3,3))
mat2 = np.random.randint(10,size=(3,2))

In [76]:
mat1

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [77]:
mat2

array([[1, 4],
       [7, 9],
       [8, 8]])

In [75]:
np.dot(mat1,mat2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [79]:
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

In [80]:
mat3

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]])

In [82]:
mat4

array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [83]:
np.dot(mat3,mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [84]:
mat3.T

array([[0, 8, 7, 0],
       [8, 7, 7, 7],
       [6, 0, 2, 2]])

In [85]:
np.dot(mat3.T,mat4)

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

In [86]:
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))

In [87]:
mat5

array([[6, 6],
       [7, 4],
       [2, 7],
       [5, 2]])

In [88]:
mat6

array([[0, 2],
       [4, 2],
       [0, 4],
       [9, 6]])

In [89]:
mat5 > mat6

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [90]:
mat5 > 7

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [91]:
np.sort(mat5)

array([[6, 6],
       [4, 7],
       [2, 7],
       [2, 5]])

In [92]:
np.argsort(mat6)

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0]], dtype=int64)

In [93]:
np.argmax(mat5)

2

In [94]:
np.max(mat5)

7

In [95]:
np.argmin(mat6)

0

In [96]:
np.min(mat6)

0

In [98]:
np.argmax(mat5, axis=1)

array([0, 0, 1, 0], dtype=int64)

In [99]:
np.random.randn(3, 5)

array([[-0.03582604,  1.56464366, -2.6197451 ,  0.8219025 ,  0.08704707],
       [-0.29900735,  0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704,  0.91540212]])

In [100]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])